### ISSUE TITLE
貌似是同步程序过多访问alist端口被限制？

### ISSUE THREAD

**Issue by gggghwje** [dr34m-cn/taosync#25]
日志如下:

Traceback (most recent call last):
  File "service\alist\alistClient.py", line 66, in req
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 700, in send
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=5244): Max retries exceeded with url: /api/admin/task/copy/info?tid=wX5YgK_WclgJD66zMAQdg (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000013D15B6FF90>: Failed to establish a new connection: [WinError 10048] 通常每个套接字地址(协议/网络地址/端口) 只允许使用一次。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "service\syncJob\jobClient.py", line 98, in updateItemStatus
  File "service\alist\alistClient.py", line 233, in taskInfo
  File "service\alist\alistClient.py", line 92, in post
  File "service\alist\alistClient.py", line 76, in req
Exception: alist连接失败，请检查是否填写正确

**Comment by dr34m-cn** [comment]
还没遇到过类似情况，当时看起来有可能是请求太快，导本地端口被占用，后边又尝试使用它，导致报错端口已被使用；应该是偶发现象，如果之后再遇到会尝试修复；
猜测你是不是设置两个同时运行的任务呢？
