### ISSUE TITLE
添加引擎，显示无法连接AList

### ISSUE THREAD

**Issue by sly199414** [dr34m-cn/taosync#28]
DDuring handling of the above exception, another exception occurred:

#Traceback (most recent call last):
>  File "service/alist/alistService.py", line 89, in addClient
<  File "service/alist/alistClient.py", line 44, in __init__
<  File "service/alist/alistClient.py", line 108, in getUser
8  File "service/alist/alistClient.py", line 101, in get
7  File "service/alist/alistClient.py", line 76, in req
;Exception: alist连接失败，请检查是否填写正确

**Comment by dr34m-cn** [comment]
这个通常是网络问题导致，使用host模式可以解决大部分问题；以下情况可能导致你无法连接
* 你的docker使用桥接模式，但是填写url时填入了`http://127.0.0.1:5244`
* 你的alist和docker没有使用同一个网卡，两个网卡无法联通
* 错误的防火墙规则限制了通信
* alist没有启动

等等类似问题导致taosync无法与alist所在网络通信

**Comment by sly199414** [comment]
已解决，感谢您的回答
